# Generated by Django 4.2 on 2024-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('society_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('bungalow', 'Bungalow'), ('flat', 'Flat'), ('rowhouse', 'Rowhouse')], max_length=10)),
                ('total_numbers', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('pan_no', models.CharField(max_length=50)),
                ('gst_no', models.CharField(max_length=50)),
                ('registration_no', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('joined_date', models.DateField()),
                ('duty_hours_from', models.TimeField()),
                ('duty_hours_to', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
