# Generated by Django 4.2 on 2024-06-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_staff', to='user.userdetails'),
        ),
        migrations.AddField(
            model_name='staff',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdetails'),
        ),
        migrations.AddField(
            model_name='staff',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='society.society'),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_staff', to='user.userdetails'),
        ),
        migrations.AddField(
            model_name='society',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_societies', to='user.userdetails'),
        ),
        migrations.AddField(
            model_name='society',
            name='society_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdetails'),
        ),
        migrations.AddField(
            model_name='society',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_societies', to='user.userdetails'),
        ),
    ]
