# Generated by Django 4.2 on 2024-06-25 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='society.society_profile'),
        ),
    ]
