# Generated by Django 4.2 on 2024-07-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('society', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyprofile',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societyprofile', to='user.society'),
        ),
    ]
