# Generated by Django 4.2 on 2024-06-27 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securitys', '0001_initial'),
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.member'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='society_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_boxes', to='society.society_profile'),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
