# Generated by Django 4.2 on 2024-06-24 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('society', '0001_initial'),
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenities_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amenity',
            name='society_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='society.society_profile'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenities_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
