# Generated by Django 4.2 on 2024-06-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='society_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='society',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
