# Generated by Django 4.2 on 2024-06-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_subadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAdmin',
        ),
    ]
