# Generated by Django 4.2 on 2024-06-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_family_type_familymember_family_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='user.society'),
        ),
    ]
