# Generated by Django 4.2 on 2024-06-26 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_member_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='society',
            name='from_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='society',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
