# Generated by Django 4.2 on 2024-06-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='society_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='society_subadmin', to='user.society'),
        ),
    ]
